
### This is an introductury notebook that will introduce us to some of the most fundamental concepts of tensors using Tensorflow
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & JNumPy
- Using @tf.function (a way to speed up regular Python functions)
- Using GPU's with Tensorflow
- Exercises to try 

## Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2023-07-30 15:42:01.177520: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.13.0


### Scalars
A scalar is simply a single number

In [2]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

2023-07-30 15:42:03.705653: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-07-30 15:42:03.728652: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-07-30 15:42:03.728907: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-07-30 15:42:03.734162: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-07-30 15:42:03.734790: I tensorflow/compile

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check number of dimensions of tensor
scalar.ndim

0

### Vectors
A vector is a number with a direction

In [4]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], 
                       [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

### Matrix
A matrix a dimensional array of numbers

In [7]:
matrix.ndim

2

In [8]:
#create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

### Tensor
an n-dimensional array of numbers

In [9]:
#Let's create a tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9,],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
tensor.ndim

3

## Creating tensors with `tf.variable`
The previous entities were created using `tf.constant`. This creates an object that cannot be changed. Going forward it will be beneficial to manipulate the contents of vectors, matrices, and tensors

In [11]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [12]:
#Let's attempt to change values in the unchangeable_tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [13]:
#Let's attempt to change values in the unchangeable_tensor
try:
    unchangeable_tensor[0].assign(7)
except Exception as e:
    print('ERROR')
    print(e)     

ERROR
'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


### Creating Random Tensors
Random tensors are tensors of some arbitrary size full of randoom numbers

In [14]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2)) 
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [15]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

### Manipulating Tensors
Let's look at several ways to change tensors we'll start with shuffling the contents of a tensor

In [16]:
not_shuffled = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]])
not_shuffled.ndim

2

In [17]:
not_shuffled.numpy()

array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)

In [18]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 8.,  9.],
       [ 3.,  2.]], dtype=float32)>

###  Tensors from Numpy Arrays
Tensors can be ran on a GPU for a massive speed boost

In [19]:
tf.ones([5, 10])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
tf.zeros([1, 6])

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [22]:
import numpy as np

#create a numpy array with values between 1 and 25 of type int 32
numpy_A = np.arange(1, 25, dtype=np.int32)

In [24]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>