
### This is an introductury notebook that will introduce us to some of the most fundamental concepts of tensors using Tensorflow
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & JNumPy
- Using @tf.function (a way to speed up regular Python functions)
- Using GPU's with Tensorflow
- Exercises to try 

## Introduction to Tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.13.0


### Scalars
A scalar is simply a single number

In [4]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#check number of dimensions of tensor
scalar.ndim

0

### Vectors
A vector is a number with a direction

In [6]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [9]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], 
                       [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

### Matrix
A matrix a dimensional array of numbers

In [10]:
matrix.ndim

2

In [12]:
#create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

### Tensor
an n-dimensional array of numbers

In [14]:
#Let's create a tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9,],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [15]:
tensor.ndim

3

## Creating tensors with `tf.variable`
The previous entities were created using `tf.constant`. This creates an object that cannot be changed. Going forward it will be beneficial to manipulate the contents of vectors, matrices, and tensors

In [17]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
#Let's attempt to change values in the unchangeable_tensor
changeable_tensor[0] = 7

<tf.Tensor: shape=(), dtype=int32, numpy=10>